#!/bin/sh

set -e

ORG=${ORG:-pgbackrest}
REPO=${REPO:-pgbackrest}
CID="$(sed -ne "/hostname/s/.*containers.\(.\{12\}\).*/\1/p" /proc/1/mountinfo)"
TARBALL=pgbackrest.tgz

if [ -z "$VERSION" ]; then
  API="https://api.github.com/repos/$ORG/$REPO/releases/latest"
else
  API="https://api.github.com/repos/$ORG/$REPO/releases/tags/release/$VERSION"
fi

URL="$(curl --silent "$API" \
  | awk \
    'BEGIN {
       FS = "\""
     }
     /tarball_url/ { 
       print $4
     }')"

curl --location --output "/$TARBALL" "$URL"
tar --strip-components 1 --exclude '*/test/' -xf "/$TARBALL" '*/src/'
cd /src
./configure --bindir=/
make -j install
strip /pgbackrest
echo "pgbackrest is built ($(/pgbackrest version))"
if [ -z "$NO_INSTRUCTIONS" ]; then
  echo "Use the following command to extract the artifact:"
  echo "  docker cp $CID:/pgbackrest ."
fi
